//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripGoHub.Web.Transfer
{
    public partial class Booking
    {
        protected global::System.Web.UI.WebControls.DropDownList RouteId;
        protected global::System.Web.UI.WebControls.TextBox PickupPoint;
        protected global::System.Web.UI.WebControls.TextBox DropoffPoint;
        protected global::System.Web.UI.WebControls.DropDownList VehicleTypeId;
        protected global::System.Web.UI.WebControls.TextBox PickupTime;
        protected global::System.Web.UI.WebControls.TextBox ReturnTime;
        protected global::System.Web.UI.WebControls.RadioButton TripOneWay;
        protected global::System.Web.UI.WebControls.RadioButton TripRound;
        protected global::System.Web.UI.WebControls.RadioButton PayOnline;
        protected global::System.Web.UI.WebControls.RadioButton PayHold;
        protected global::System.Web.UI.WebControls.TextBox CustomerName;
        protected global::System.Web.UI.WebControls.TextBox CustomerPhone;
        protected global::System.Web.UI.WebControls.TextBox CustomerEmail;
        protected global::System.Web.UI.WebControls.TextBox Note;
        protected global::System.Web.UI.WebControls.Button BtnSubmit;
        protected global::System.Web.UI.WebControls.Panel MessagePanel;
        protected global::System.Web.UI.WebControls.Literal MessageText;
        protected global::System.Web.UI.WebControls.Literal RouteDataJson;
    }
}
