INSERT INTO dbo.tgh_country (Iso2, Iso3, PhoneCode, IsDefault, Status, SortOrder, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy)
VALUES
(N'AF', N'AFG', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AX', N'ALA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AL', N'ALB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'DZ', N'DZA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AS', N'ASM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AD', N'AND', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AO', N'AGO', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AI', N'AIA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AQ', N'ATA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AG', N'ATG', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AR', N'ARG', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AM', N'ARM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AW', N'ABW', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AU', N'AUS', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AT', N'AUT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AZ', N'AZE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BS', N'BHS', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BH', N'BHR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BD', N'BGD', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BB', N'BRB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BY', N'BLR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BE', N'BEL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BZ', N'BLZ', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BJ', N'BEN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BM', N'BMU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BT', N'BTN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BO', N'BOL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BQ', N'BES', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BA', N'BIH', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BW', N'BWA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BV', N'BVT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BR', N'BRA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IO', N'IOT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'VG', N'VGB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BN', N'BRN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BG', N'BGR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BF', N'BFA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BI', N'BDI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CV', N'CPV', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KH', N'KHM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CM', N'CMR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CA', N'CAN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KY', N'CYM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CF', N'CAF', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TD', N'TCD', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CL', N'CHL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CN', N'CHN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'HK', N'HKG', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MO', N'MAC', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CX', N'CXR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CC', N'CCK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CO', N'COL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KM', N'COM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CG', N'COG', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CK', N'COK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CR', N'CRI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'HR', N'HRV', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CU', N'CUB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CW', N'CUW', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CY', N'CYP', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CZ', N'CZE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KP', N'PRK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CD', N'COD', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'DK', N'DNK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'DJ', N'DJI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'DM', N'DMA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'DO', N'DOM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'EC', N'ECU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'EG', N'EGY', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SV', N'SLV', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GQ', N'GNQ', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ER', N'ERI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'EE', N'EST', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SZ', N'SWZ', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ET', N'ETH', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'FK', N'FLK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'FO', N'FRO', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'FJ', N'FJI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'FI', N'FIN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'FR', N'FRA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GF', N'GUF', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PF', N'PYF', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TF', N'ATF', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GA', N'GAB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GM', N'GMB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GE', N'GEO', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'DE', N'DEU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GH', N'GHA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GI', N'GIB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GR', N'GRC', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GL', N'GRL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GD', N'GRD', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GP', N'GLP', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GU', N'GUM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GT', N'GTM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GG', N'GGY', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GN', N'GIN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GW', N'GNB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GY', N'GUY', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'HT', N'HTI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'HM', N'HMD', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'VA', N'VAT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'HN', N'HND', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'HU', N'HUN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IS', N'ISL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IN', N'IND', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ID', N'IDN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IR', N'IRN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IQ', N'IRQ', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IE', N'IRL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IM', N'IMN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IL', N'ISR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'IT', N'ITA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CI', N'CIV', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'JM', N'JAM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'JP', N'JPN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'JE', N'JEY', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'JO', N'JOR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KZ', N'KAZ', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KE', N'KEN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KI', N'KIR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KW', N'KWT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KG', N'KGZ', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LA', N'LAO', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LV', N'LVA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LB', N'LBN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LS', N'LSO', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LR', N'LBR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LY', N'LBY', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LI', N'LIE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LT', N'LTU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LU', N'LUX', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MG', N'MDG', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MW', N'MWI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MY', N'MYS', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MV', N'MDV', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ML', N'MLI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MT', N'MLT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MH', N'MHL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MQ', N'MTQ', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MR', N'MRT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MU', N'MUS', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'YT', N'MYT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MX', N'MEX', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'FM', N'FSM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MC', N'MCO', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MN', N'MNG', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ME', N'MNE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MS', N'MSR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MA', N'MAR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MZ', N'MOZ', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MM', N'MMR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NA', N'NAM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NR', N'NRU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NP', N'NPL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NL', N'NLD', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NC', N'NCL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NZ', N'NZL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NI', N'NIC', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NE', N'NER', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NG', N'NGA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NU', N'NIU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NF', N'NFK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MP', N'MNP', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MK', N'MKD', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'NO', N'NOR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'OM', N'OMN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PK', N'PAK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PW', N'PLW', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PA', N'PAN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PG', N'PNG', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PY', N'PRY', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PE', N'PER', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PH', N'PHL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PN', N'PCN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PL', N'POL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PT', N'PRT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PR', N'PRI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'QA', N'QAT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KR', N'KOR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MD', N'MDA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'RE', N'REU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'RO', N'ROU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'RU', N'RUS', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'RW', N'RWA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'BL', N'BLM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SH', N'SHN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'KN', N'KNA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LC', N'LCA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'MF', N'MAF', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PM', N'SPM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'VC', N'VCT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'WS', N'WSM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SM', N'SMR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ST', N'STP', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SA', N'SAU', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SN', N'SEN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'RS', N'SRB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SC', N'SYC', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SL', N'SLE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SG', N'SGP', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SX', N'SXM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SK', N'SVK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SI', N'SVN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SB', N'SLB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SO', N'SOM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ZA', N'ZAF', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GS', N'SGS', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SS', N'SSD', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ES', N'ESP', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'LK', N'LKA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'PS', N'PSE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SD', N'SDN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SR', N'SUR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SJ', N'SJM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SE', N'SWE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'CH', N'CHE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'SY', N'SYR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TW', N'TWN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TJ', N'TJK', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TH', N'THA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TL', N'TLS', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TG', N'TGO', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TK', N'TKL', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TO', N'TON', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TT', N'TTO', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TN', N'TUN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TR', N'TUR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TM', N'TKM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TC', N'TCA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TV', N'TUV', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'UG', N'UGA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'UA', N'UKR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'AE', N'ARE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'GB', N'GBR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'TZ', N'TZA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'UM', N'UMI', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'US', N'USA', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'VI', N'VIR', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'UY', N'URY', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'UZ', N'UZB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'VU', N'VUT', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'VE', N'VEN', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'VN', N'VNM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'WF', N'WLF', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'EH', N'ESH', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'YE', N'YEM', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ZM', N'ZMB', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'),
(N'ZW', N'ZWE', NULL, 0, 1, 0, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system');

UPDATE dbo.tgh_country SET IsDefault = 1 WHERE Iso2 = N'VN';

INSERT INTO dbo.tgh_country_lang (CountryId, Lang, Name, NativeName, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy)
SELECT c.CountryId, N'vi', v.Name, v.Name, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'
FROM (VALUES
(N'AF', N'Afghanistan'),
(N'AX', N'Åland Islands'),
(N'AL', N'Albania'),
(N'DZ', N'Algeria'),
(N'AS', N'American Samoa'),
(N'AD', N'Andorra'),
(N'AO', N'Angola'),
(N'AI', N'Anguilla'),
(N'AQ', N'Antarctica'),
(N'AG', N'Antigua and Barbuda'),
(N'AR', N'Argentina'),
(N'AM', N'Armenia'),
(N'AW', N'Aruba'),
(N'AU', N'Australia'),
(N'AT', N'Austria'),
(N'AZ', N'Azerbaijan'),
(N'BS', N'Bahamas'),
(N'BH', N'Bahrain'),
(N'BD', N'Bangladesh'),
(N'BB', N'Barbados'),
(N'BY', N'Belarus'),
(N'BE', N'Belgium'),
(N'BZ', N'Belize'),
(N'BJ', N'Benin'),
(N'BM', N'Bermuda'),
(N'BT', N'Bhutan'),
(N'BO', N'Bolivia, Plurinational State of'),
(N'BQ', N'Bonaire, Sint Eustatius and Saba'),
(N'BA', N'Bosnia and Herzegovina'),
(N'BW', N'Botswana'),
(N'BV', N'Bouvet Island'),
(N'BR', N'Brazil'),
(N'IO', N'British Indian Ocean Territory'),
(N'VG', N'Virgin Islands, British'),
(N'BN', N'Brunei Darussalam'),
(N'BG', N'Bulgaria'),
(N'BF', N'Burkina Faso'),
(N'BI', N'Burundi'),
(N'CV', N'Cape Verde'),
(N'KH', N'Cambodia'),
(N'CM', N'Cameroon'),
(N'CA', N'Canada'),
(N'KY', N'Cayman Islands'),
(N'CF', N'Central African Republic'),
(N'TD', N'Chad'),
(N'CL', N'Chile'),
(N'CN', N'China'),
(N'HK', N'Hong Kong'),
(N'MO', N'Macao'),
(N'CX', N'Christmas Island'),
(N'CC', N'Cocos (Keeling) Islands'),
(N'CO', N'Colombia'),
(N'KM', N'Comoros'),
(N'CG', N'Congo'),
(N'CK', N'Cook Islands'),
(N'CR', N'Costa Rica'),
(N'HR', N'Croatia'),
(N'CU', N'Cuba'),
(N'CW', N'Curaçao'),
(N'CY', N'Cyprus'),
(N'CZ', N'Czech Republic'),
(N'KP', N'Korea, Democratic People''s Republic of'),
(N'CD', N'Congo, the Democratic Republic of the'),
(N'DK', N'Denmark'),
(N'DJ', N'Djibouti'),
(N'DM', N'Dominica'),
(N'DO', N'Dominican Republic'),
(N'EC', N'Ecuador'),
(N'EG', N'Egypt'),
(N'SV', N'El Salvador'),
(N'GQ', N'Equatorial Guinea'),
(N'ER', N'Eritrea'),
(N'EE', N'Estonia'),
(N'SZ', N'Eswatini'),
(N'ET', N'Ethiopia'),
(N'FK', N'Falkland Islands (Malvinas)'),
(N'FO', N'Faroe Islands'),
(N'FJ', N'Fiji'),
(N'FI', N'Finland'),
(N'FR', N'France'),
(N'GF', N'French Guiana'),
(N'PF', N'French Polynesia'),
(N'TF', N'French Southern Territories'),
(N'GA', N'Gabon'),
(N'GM', N'Gambia'),
(N'GE', N'Georgia'),
(N'DE', N'Germany'),
(N'GH', N'Ghana'),
(N'GI', N'Gibraltar'),
(N'GR', N'Greece'),
(N'GL', N'Greenland'),
(N'GD', N'Grenada'),
(N'GP', N'Guadeloupe'),
(N'GU', N'Guam'),
(N'GT', N'Guatemala'),
(N'GG', N'Guernsey'),
(N'GN', N'Guinea'),
(N'GW', N'Guinea-Bissau'),
(N'GY', N'Guyana'),
(N'HT', N'Haiti'),
(N'HM', N'Heard Island and McDonald Islands'),
(N'VA', N'Holy See (Vatican City State)'),
(N'HN', N'Honduras'),
(N'HU', N'Hungary'),
(N'IS', N'Iceland'),
(N'IN', N'India'),
(N'ID', N'Indonesia'),
(N'IR', N'Iran, Islamic Republic of'),
(N'IQ', N'Iraq'),
(N'IE', N'Ireland'),
(N'IM', N'Isle of Man'),
(N'IL', N'Israel'),
(N'IT', N'Italy'),
(N'CI', N'Côte d''Ivoire'),
(N'JM', N'Jamaica'),
(N'JP', N'Japan'),
(N'JE', N'Jersey'),
(N'JO', N'Jordan'),
(N'KZ', N'Kazakhstan'),
(N'KE', N'Kenya'),
(N'KI', N'Kiribati'),
(N'KW', N'Kuwait'),
(N'KG', N'Kyrgyzstan'),
(N'LA', N'Lao People''s Democratic Republic'),
(N'LV', N'Latvia'),
(N'LB', N'Lebanon'),
(N'LS', N'Lesotho'),
(N'LR', N'Liberia'),
(N'LY', N'Libya'),
(N'LI', N'Liechtenstein'),
(N'LT', N'Lithuania'),
(N'LU', N'Luxembourg'),
(N'MG', N'Madagascar'),
(N'MW', N'Malawi'),
(N'MY', N'Malaysia'),
(N'MV', N'Maldives'),
(N'ML', N'Mali'),
(N'MT', N'Malta'),
(N'MH', N'Marshall Islands'),
(N'MQ', N'Martinique'),
(N'MR', N'Mauritania'),
(N'MU', N'Mauritius'),
(N'YT', N'Mayotte'),
(N'MX', N'Mexico'),
(N'FM', N'Micronesia, Federated States of'),
(N'MC', N'Monaco'),
(N'MN', N'Mongolia'),
(N'ME', N'Montenegro'),
(N'MS', N'Montserrat'),
(N'MA', N'Morocco'),
(N'MZ', N'Mozambique'),
(N'MM', N'Myanmar'),
(N'NA', N'Namibia'),
(N'NR', N'Nauru'),
(N'NP', N'Nepal'),
(N'NL', N'Netherlands'),
(N'NC', N'New Caledonia'),
(N'NZ', N'New Zealand'),
(N'NI', N'Nicaragua'),
(N'NE', N'Niger'),
(N'NG', N'Nigeria'),
(N'NU', N'Niue'),
(N'NF', N'Norfolk Island'),
(N'MP', N'Northern Mariana Islands'),
(N'MK', N'Macedonia, the Former Yugoslav Republic of'),
(N'NO', N'Norway'),
(N'OM', N'Oman'),
(N'PK', N'Pakistan'),
(N'PW', N'Palau'),
(N'PA', N'Panama'),
(N'PG', N'Papua New Guinea'),
(N'PY', N'Paraguay'),
(N'PE', N'Peru'),
(N'PH', N'Philippines'),
(N'PN', N'Pitcairn'),
(N'PL', N'Poland'),
(N'PT', N'Portugal'),
(N'PR', N'Puerto Rico'),
(N'QA', N'Qatar'),
(N'KR', N'Korea, Republic of'),
(N'MD', N'Moldova, Republic of'),
(N'RE', N'Réunion'),
(N'RO', N'Romania'),
(N'RU', N'Russian Federation'),
(N'RW', N'Rwanda'),
(N'BL', N'Saint Barthélemy'),
(N'SH', N'Saint Helena, Ascension and Tristan da Cunha'),
(N'KN', N'Saint Kitts and Nevis'),
(N'LC', N'Saint Lucia'),
(N'MF', N'Saint Martin (French part)'),
(N'PM', N'Saint Pierre and Miquelon'),
(N'VC', N'Saint Vincent and the Grenadines'),
(N'WS', N'Samoa'),
(N'SM', N'San Marino'),
(N'ST', N'Sao Tome and Principe'),
(N'SA', N'Saudi Arabia'),
(N'SN', N'Senegal'),
(N'RS', N'Serbia'),
(N'SC', N'Seychelles'),
(N'SL', N'Sierra Leone'),
(N'SG', N'Singapore'),
(N'SX', N'Sint Maarten (Dutch part)'),
(N'SK', N'Slovakia'),
(N'SI', N'Slovenia'),
(N'SB', N'Solomon Islands'),
(N'SO', N'Somalia'),
(N'ZA', N'South Africa'),
(N'GS', N'South Georgia and the South Sandwich Islands'),
(N'SS', N'South Sudan'),
(N'ES', N'Spain'),
(N'LK', N'Sri Lanka'),
(N'PS', N'Palestine, State of'),
(N'SD', N'Sudan'),
(N'SR', N'Suriname'),
(N'SJ', N'Svalbard and Jan Mayen'),
(N'SE', N'Sweden'),
(N'CH', N'Switzerland'),
(N'SY', N'Syrian Arab Republic'),
(N'TW', N'Taiwan, Province of China'),
(N'TJ', N'Tajikistan'),
(N'TH', N'Thailand'),
(N'TL', N'Timor-Leste'),
(N'TG', N'Togo'),
(N'TK', N'Tokelau'),
(N'TO', N'Tonga'),
(N'TT', N'Trinidad and Tobago'),
(N'TN', N'Tunisia'),
(N'TR', N'Turkey'),
(N'TM', N'Turkmenistan'),
(N'TC', N'Turks and Caicos Islands'),
(N'TV', N'Tuvalu'),
(N'UG', N'Uganda'),
(N'UA', N'Ukraine'),
(N'AE', N'United Arab Emirates'),
(N'GB', N'United Kingdom'),
(N'TZ', N'Tanzania, United Republic of'),
(N'UM', N'United States Minor Outlying Islands'),
(N'US', N'United States'),
(N'VI', N'Virgin Islands, U.S.'),
(N'UY', N'Uruguay'),
(N'UZ', N'Uzbekistan'),
(N'VU', N'Vanuatu'),
(N'VE', N'Venezuela, Bolivarian Republic of'),
(N'VN', N'Viet Nam'),
(N'WF', N'Wallis and Futuna'),
(N'EH', N'Western Sahara'),
(N'YE', N'Yemen'),
(N'ZM', N'Zambia'),
(N'ZW', N'Zimbabwe')) AS v(Iso2, Name)
JOIN dbo.tgh_country c ON c.Iso2 = v.Iso2;

INSERT INTO dbo.tgh_country_lang (CountryId, Lang, Name, NativeName, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy)
SELECT c.CountryId, N'en', v.Name, v.Name, SYSUTCDATETIME(), N'system', SYSUTCDATETIME(), N'system'
FROM (VALUES
(N'AF', N'Afghanistan'),
(N'AX', N'Åland Islands'),
(N'AL', N'Albania'),
(N'DZ', N'Algeria'),
(N'AS', N'American Samoa'),
(N'AD', N'Andorra'),
(N'AO', N'Angola'),
(N'AI', N'Anguilla'),
(N'AQ', N'Antarctica'),
(N'AG', N'Antigua and Barbuda'),
(N'AR', N'Argentina'),
(N'AM', N'Armenia'),
(N'AW', N'Aruba'),
(N'AU', N'Australia'),
(N'AT', N'Austria'),
(N'AZ', N'Azerbaijan'),
(N'BS', N'Bahamas'),
(N'BH', N'Bahrain'),
(N'BD', N'Bangladesh'),
(N'BB', N'Barbados'),
(N'BY', N'Belarus'),
(N'BE', N'Belgium'),
(N'BZ', N'Belize'),
(N'BJ', N'Benin'),
(N'BM', N'Bermuda'),
(N'BT', N'Bhutan'),
(N'BO', N'Bolivia, Plurinational State of'),
(N'BQ', N'Bonaire, Sint Eustatius and Saba'),
(N'BA', N'Bosnia and Herzegovina'),
(N'BW', N'Botswana'),
(N'BV', N'Bouvet Island'),
(N'BR', N'Brazil'),
(N'IO', N'British Indian Ocean Territory'),
(N'VG', N'Virgin Islands, British'),
(N'BN', N'Brunei Darussalam'),
(N'BG', N'Bulgaria'),
(N'BF', N'Burkina Faso'),
(N'BI', N'Burundi'),
(N'CV', N'Cape Verde'),
(N'KH', N'Cambodia'),
(N'CM', N'Cameroon'),
(N'CA', N'Canada'),
(N'KY', N'Cayman Islands'),
(N'CF', N'Central African Republic'),
(N'TD', N'Chad'),
(N'CL', N'Chile'),
(N'CN', N'China'),
(N'HK', N'Hong Kong'),
(N'MO', N'Macao'),
(N'CX', N'Christmas Island'),
(N'CC', N'Cocos (Keeling) Islands'),
(N'CO', N'Colombia'),
(N'KM', N'Comoros'),
(N'CG', N'Congo'),
(N'CK', N'Cook Islands'),
(N'CR', N'Costa Rica'),
(N'HR', N'Croatia'),
(N'CU', N'Cuba'),
(N'CW', N'Curaçao'),
(N'CY', N'Cyprus'),
(N'CZ', N'Czech Republic'),
(N'KP', N'Korea, Democratic People''s Republic of'),
(N'CD', N'Congo, the Democratic Republic of the'),
(N'DK', N'Denmark'),
(N'DJ', N'Djibouti'),
(N'DM', N'Dominica'),
(N'DO', N'Dominican Republic'),
(N'EC', N'Ecuador'),
(N'EG', N'Egypt'),
(N'SV', N'El Salvador'),
(N'GQ', N'Equatorial Guinea'),
(N'ER', N'Eritrea'),
(N'EE', N'Estonia'),
(N'SZ', N'Eswatini'),
(N'ET', N'Ethiopia'),
(N'FK', N'Falkland Islands (Malvinas)'),
(N'FO', N'Faroe Islands'),
(N'FJ', N'Fiji'),
(N'FI', N'Finland'),
(N'FR', N'France'),
(N'GF', N'French Guiana'),
(N'PF', N'French Polynesia'),
(N'TF', N'French Southern Territories'),
(N'GA', N'Gabon'),
(N'GM', N'Gambia'),
(N'GE', N'Georgia'),
(N'DE', N'Germany'),
(N'GH', N'Ghana'),
(N'GI', N'Gibraltar'),
(N'GR', N'Greece'),
(N'GL', N'Greenland'),
(N'GD', N'Grenada'),
(N'GP', N'Guadeloupe'),
(N'GU', N'Guam'),
(N'GT', N'Guatemala'),
(N'GG', N'Guernsey'),
(N'GN', N'Guinea'),
(N'GW', N'Guinea-Bissau'),
(N'GY', N'Guyana'),
(N'HT', N'Haiti'),
(N'HM', N'Heard Island and McDonald Islands'),
(N'VA', N'Holy See (Vatican City State)'),
(N'HN', N'Honduras'),
(N'HU', N'Hungary'),
(N'IS', N'Iceland'),
(N'IN', N'India'),
(N'ID', N'Indonesia'),
(N'IR', N'Iran, Islamic Republic of'),
(N'IQ', N'Iraq'),
(N'IE', N'Ireland'),
(N'IM', N'Isle of Man'),
(N'IL', N'Israel'),
(N'IT', N'Italy'),
(N'CI', N'Côte d''Ivoire'),
(N'JM', N'Jamaica'),
(N'JP', N'Japan'),
(N'JE', N'Jersey'),
(N'JO', N'Jordan'),
(N'KZ', N'Kazakhstan'),
(N'KE', N'Kenya'),
(N'KI', N'Kiribati'),
(N'KW', N'Kuwait'),
(N'KG', N'Kyrgyzstan'),
(N'LA', N'Lao People''s Democratic Republic'),
(N'LV', N'Latvia'),
(N'LB', N'Lebanon'),
(N'LS', N'Lesotho'),
(N'LR', N'Liberia'),
(N'LY', N'Libya'),
(N'LI', N'Liechtenstein'),
(N'LT', N'Lithuania'),
(N'LU', N'Luxembourg'),
(N'MG', N'Madagascar'),
(N'MW', N'Malawi'),
(N'MY', N'Malaysia'),
(N'MV', N'Maldives'),
(N'ML', N'Mali'),
(N'MT', N'Malta'),
(N'MH', N'Marshall Islands'),
(N'MQ', N'Martinique'),
(N'MR', N'Mauritania'),
(N'MU', N'Mauritius'),
(N'YT', N'Mayotte'),
(N'MX', N'Mexico'),
(N'FM', N'Micronesia, Federated States of'),
(N'MC', N'Monaco'),
(N'MN', N'Mongolia'),
(N'ME', N'Montenegro'),
(N'MS', N'Montserrat'),
(N'MA', N'Morocco'),
(N'MZ', N'Mozambique'),
(N'MM', N'Myanmar'),
(N'NA', N'Namibia'),
(N'NR', N'Nauru'),
(N'NP', N'Nepal'),
(N'NL', N'Netherlands'),
(N'NC', N'New Caledonia'),
(N'NZ', N'New Zealand'),
(N'NI', N'Nicaragua'),
(N'NE', N'Niger'),
(N'NG', N'Nigeria'),
(N'NU', N'Niue'),
(N'NF', N'Norfolk Island'),
(N'MP', N'Northern Mariana Islands'),
(N'MK', N'Macedonia, the Former Yugoslav Republic of'),
(N'NO', N'Norway'),
(N'OM', N'Oman'),
(N'PK', N'Pakistan'),
(N'PW', N'Palau'),
(N'PA', N'Panama'),
(N'PG', N'Papua New Guinea'),
(N'PY', N'Paraguay'),
(N'PE', N'Peru'),
(N'PH', N'Philippines'),
(N'PN', N'Pitcairn'),
(N'PL', N'Poland'),
(N'PT', N'Portugal'),
(N'PR', N'Puerto Rico'),
(N'QA', N'Qatar'),
(N'KR', N'Korea, Republic of'),
(N'MD', N'Moldova, Republic of'),
(N'RE', N'Réunion'),
(N'RO', N'Romania'),
(N'RU', N'Russian Federation'),
(N'RW', N'Rwanda'),
(N'BL', N'Saint Barthélemy'),
(N'SH', N'Saint Helena, Ascension and Tristan da Cunha'),
(N'KN', N'Saint Kitts and Nevis'),
(N'LC', N'Saint Lucia'),
(N'MF', N'Saint Martin (French part)'),
(N'PM', N'Saint Pierre and Miquelon'),
(N'VC', N'Saint Vincent and the Grenadines'),
(N'WS', N'Samoa'),
(N'SM', N'San Marino'),
(N'ST', N'Sao Tome and Principe'),
(N'SA', N'Saudi Arabia'),
(N'SN', N'Senegal'),
(N'RS', N'Serbia'),
(N'SC', N'Seychelles'),
(N'SL', N'Sierra Leone'),
(N'SG', N'Singapore'),
(N'SX', N'Sint Maarten (Dutch part)'),
(N'SK', N'Slovakia'),
(N'SI', N'Slovenia'),
(N'SB', N'Solomon Islands'),
(N'SO', N'Somalia'),
(N'ZA', N'South Africa'),
(N'GS', N'South Georgia and the South Sandwich Islands'),
(N'SS', N'South Sudan'),
(N'ES', N'Spain'),
(N'LK', N'Sri Lanka'),
(N'PS', N'Palestine, State of'),
(N'SD', N'Sudan'),
(N'SR', N'Suriname'),
(N'SJ', N'Svalbard and Jan Mayen'),
(N'SE', N'Sweden'),
(N'CH', N'Switzerland'),
(N'SY', N'Syrian Arab Republic'),
(N'TW', N'Taiwan, Province of China'),
(N'TJ', N'Tajikistan'),
(N'TH', N'Thailand'),
(N'TL', N'Timor-Leste'),
(N'TG', N'Togo'),
(N'TK', N'Tokelau'),
(N'TO', N'Tonga'),
(N'TT', N'Trinidad and Tobago'),
(N'TN', N'Tunisia'),
(N'TR', N'Turkey'),
(N'TM', N'Turkmenistan'),
(N'TC', N'Turks and Caicos Islands'),
(N'TV', N'Tuvalu'),
(N'UG', N'Uganda'),
(N'UA', N'Ukraine'),
(N'AE', N'United Arab Emirates'),
(N'GB', N'United Kingdom'),
(N'TZ', N'Tanzania, United Republic of'),
(N'UM', N'United States Minor Outlying Islands'),
(N'US', N'United States'),
(N'VI', N'Virgin Islands, U.S.'),
(N'UY', N'Uruguay'),
(N'UZ', N'Uzbekistan'),
(N'VU', N'Vanuatu'),
(N'VE', N'Venezuela, Bolivarian Republic of'),
(N'VN', N'Viet Nam'),
(N'WF', N'Wallis and Futuna'),
(N'EH', N'Western Sahara'),
(N'YE', N'Yemen'),
(N'ZM', N'Zambia'),
(N'ZW', N'Zimbabwe')) AS v(Iso2, Name)
JOIN dbo.tgh_country c ON c.Iso2 = v.Iso2;

