//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripGoHub.Web.Admin
{
    public partial class AdminMaster
    {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;
        protected global::System.Web.UI.WebControls.Label LblUser;
        protected global::System.Web.UI.WebControls.Button BtnLogout;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor menuDashboard;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor menuProvinces;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor menuWards;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder Scripts;
    }
}
